site_name: Concourse Tutorial by Stark & Wayne
pages:
  - Introduction: index.md
  - Hello World: 01_task_hello_world.md
  - Task Inputs: 02_task_inputs.md
  - Task Scripts: 03_task_scripts.md
  - Basic Pipeline: 04_basic_pipeline.md
  - Hello World Pipeline: 05_pipeline_task_hello_world.md
  - Watch Job Output: 06_watch_job_output.md
  - Trigger Jobs with API: 07_trigger_jobs_with_api.md
  - Triggers: 08_triggers.md
  - Destroying Pipelines: 09_destroy_pipelines.md
  - Job Inputs: 10_job_inputs.md
  - Outputs to Inputs: 11_task_outputs_to_inputs.md
  - Publishing Outputs: 12_publishing_outputs.md
  - Pipeline Jobs: 13_pipeline_jobs.md
  - Parameters: 14_parameters.md

theme: 'material'
theme_dir: 'theme-overrides'

extra:
  palette:
    primary: 'orange'
    accent: 'amber'
  feature:
    tabs: true

  font:
    text: 'Bitter' # https://fonts.google.com/specimen/Bitter
    code: 'Ubuntu Mono'

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.critic
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.superfences
  - toc(permalink=true)

repo_name: 'help fix the tutorials'
repo_url: 'https://github.com/starkandwayne/concourse-tutorial'
edit_uri: edit/master/docs/
extra_css: [print.css]
